// Subset the template's Font Awesome Pro fonts down to the icons this site actually uses.
// Re-run after adding/removing `fa-*` classes in src/ or FA `content:` codes in src/styles:
//   bun run icons:subset
import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
// @ts-expect-error subset-font ships no type declarations
import subsetFont from "subset-font";

const FA = "averix-modern-creative-agency-html-template-2026-06-19-09-20-31-utc/template-for-landing/averix/assets";
const STYLES = ["regular-400", "solid-900", "brands-400"] as const;
// Classes that are style/modifier helpers, not glyphs.
const NOT_ICONS = new Set(["fa-regular", "fa-solid", "fa-brands", "fa-sharp", "fa-light", "fa-thin"]);

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((e) => (e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)])),
  );
  return nested.flat();
}

const css = await readFile(join(FA, "css/font-awesome-pro.css"), "utf8");
const files = (await walk("src")).filter((f) => /\.(astro|ts|scss|md|json)$/.test(f) && !f.endsWith("_icons.scss"));

const names = new Set<string>();
const codepoints = new Set<number>();
for (const f of files) {
  const text = await readFile(f, "utf8");
  for (const m of text.matchAll(/\bfa-[a-z0-9-]+/g)) if (!NOT_ICONS.has(m[0])) names.add(m[0]);
  for (const m of text.matchAll(/content:\s*"\\([ef][0-9a-f]{3})"/gi)) codepoints.add(parseInt(m[1], 16));
}

const rules: string[] = [];
for (const name of [...names].sort()) {
  const m = css.match(new RegExp(`\\.${name}:before[^{]*\\{content:"\\\\([0-9a-f]+)"`));
  if (!m) { console.warn(`unknown icon: ${name}`); continue; }
  codepoints.add(parseInt(m[1], 16));
  rules.push(`.${name}::before { content: "\\${m[1]}"; }`);
}

const text = String.fromCodePoint(...codepoints);
for (const style of STYLES) {
  const src = await readFile(join(FA, `fonts/fa-${style}.woff2`));
  const out = await subsetFont(src, text, { targetFormat: "woff2" });
  await writeFile(`src/assets/fonts/fa-${style}.woff2`, out);
  console.log(`fa-${style}.woff2: ${out.length} bytes`);
}

const face = (family: string, weight: number, file: string) =>
  `@font-face { font-family: "${family}"; font-style: normal; font-weight: ${weight}; font-display: block; src: url("/src/assets/fonts/${file}") format("woff2"); }`;

await writeFile(
  "src/styles/components/_icons.scss",
  `// GENERATED by scripts/subset-icons.ts — do not edit by hand.
${face("Font Awesome 6 Pro", 400, "fa-regular-400.woff2")}
${face("Font Awesome 6 Pro", 900, "fa-solid-900.woff2")}
${face("Font Awesome 6 Brands", 400, "fa-brands-400.woff2")}
.fa-regular, .fa-solid, .fa-brands, .fa-sharp { -moz-osx-font-smoothing: grayscale; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; line-height: 1; text-rendering: auto; }
.fa-regular, .fa-sharp { font-family: "Font Awesome 6 Pro"; font-weight: 400; }
.fa-solid { font-family: "Font Awesome 6 Pro"; font-weight: 900; }
.fa-brands { font-family: "Font Awesome 6 Brands"; font-weight: 400; }
${rules.join("\n")}
`,
);
console.log(`icons: ${rules.length} classes, ${codepoints.size} glyphs`);
